# Generated by Django 5.0.4 on 2024-05-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='numeroHoras',
            field=models.IntegerField(default=0),
        ),
    ]
